{% set name = "liquidpy" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/liquidpy-{{ version }}.tar.gz
  sha256: ff7c1752bed93f4e2e90b35919b081e50ad290b82acbd4402c6fa37b2762a497
  patches:
    # use poetry-core
    - poetry-core.patch

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0.0
    - jinja2 >=3.0.0,<4.0.0

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - liquid
  commands:
    - python -m pip check

about:
  home: https://github.com/pwwang/liquidpy
  doc_url: https://pwwang.github.io/liquidpy/
  dev_url: https://github.com/pwwang/liquidpy.git
  summary: A port of liquid template engine for python
  license: Apache-2.0
  license_file: LICENSE
  description: A port of liquid template engine for python. This is compatible with standard Liquid template engine. Variations, such as Shopify and Jekyll are not fully supported yet.

extra:
  recipe-maintainers:
    - jan-janssen
    - duncanmmacleod
